version: "3.9"

services:
  chatbot-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-api
    ports:
      - "6002:6002"
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=AIzaSyCA45LFI3V2w78b3FOeEvq0yrJe-VVm9VY
